version: 2
project_name: uuidv7
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  # TODO: tinygo
  # - id: uuidv7-tiny
  #   main: ./cmd/
  #   gobinary: tinygo
  #   goos:
  #     - darwin
  #     - linux
  #     - windows
  #   goarch:
  #     - amd64
  #     - arm64
  - id: uuidv7-all
    main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - aix
      - darwin
      - dragonfly
      - freebsd
      - illumos
      - js
      - linux
      - netbsd
      - openbsd
      - plan9
      - solaris
      - wasip1
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - loong64
      - mips
      - mips64
      - mips64le
      - mipsle
      - ppc64
      - ppc64le
      - riscv64
      - s390x
      - wasm
    goarm:
      - 6
      - 7
    goamd64:
      - v1
      - v2
      - v3
      - v4
  - id: uuidv7-ios-with-sdk
    main: ./cmd/
    env:
      - CGO_ENABLED=1
    goos:
      - ios
    goarch:
      - arm64
  - id: uuidv7-android-no-sdk
    main: ./cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - android
    goarch:
      - arm64
archives:
  - id: uuidv7
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
